AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.handler
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Runtime: python3.11
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  Api:
    Type: AWS::Serverless::HttpApi

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
